### ISSUE TITLE
ConvertStructuredToProvider.cs errors Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by wgbrown** [m-kovalsky/Tabular#11]
I get the following error

![image](https://user-images.githubusercontent.com/10822387/154198433-993e87de-83ba-4347-8c2f-7cdc679d11eb.png)

On line: foreach (var p in t.Partitions.Where(a => a.DataSource.Name == strdsName).ToList())

I can't determine how the DataSource.name in partition object is resolved.  (My C# is limited).  But the datasourcename appears to live in the M Script?

**Comment by m-kovalsky** [comment]
After reviewing this feedback one more time (and having written this code some time ago), I realized that your request is not part of the scope of this code. Make sure to read this [blog post](https://www.elegantbi.com/post/convertdatasources) as to the purpose of this code. To recap, this code is to convert structured data sources to legacy data sources where the partitions are simply SQL code (not M). In your example, the partitions are using M-code.

**Comment by wgbrown** [comment]
thanks, glossed over that detail.  Sorry for the trouble.
