### ISSUE TITLE
Doesn't work with PPU

### ISSUE THREAD

**Issue by FrankFromGermany** [m-kovalsky/Tabular#2]
Is a Service Principal required for running this script?

As Power BI Admin I still get this:
Error on line 29 ( Model.Database.TOMDatabase.Server.CancelSession(sID);)
The '<pii>joe@abc.com</pii>' user does not have permission to perform a cancel operation.

**Comment by m-kovalsky** [comment]
Yes, you will need to set up a service principal if using Power BI Premium. Can follow the steps in this article.

https://tabulareditor.com/2020/06/02/PBI-SP-Access.html
