### ISSUE TITLE
Unable to run script against report 

### ISSUE THREAD

**Issue by cptshrk108** [m-kovalsky/Tabular#20]
I'm facing an issue when pointing to a OneDrive path. Have you resolved your issue?

I'm getting an error at line 137: File does not exist. Must use a valid .pbix or .pbit file. 

Not facing this issue when moving the file to a local folder.

**Comment by m-kovalsky** [comment]
This is for the ExportReportObjects script? Did you set the sensitivity level and are you using the latest version of the script? I use this script with my files from OneDrive exclusively and it works just fine.

**Comment by cptshrk108** [comment]
Well, I ran it again today and it worked perfectly :)

Maybe there was an issue with the onedrive synching a file.
