### ISSUE TITLE
ArgumentNullException

### ISSUE THREAD

**Issue by shubham091294** [m-kovalsky/Tabular#21]
I am getting an error on line 50. Could you please help me navigate through it? 
![image](https://user-images.githubusercontent.com/37980342/227009339-57b8c3e4-4e13-4bf8-b802-f6d710dd33c0.png)

I don't have one data source but data is pulled in using dataflows and then creating the model in PowerBI
![image](https://user-images.githubusercontent.com/37980342/227016677-14c3909b-955e-4dbc-8b26-c08832bcc8be.png)

**Comment by m-kovalsky** [comment]
Please try v1.1.2 of the [AutoAggs script](https://github.com/m-kovalsky/Tabular/blob/master/AutoAggs/AutoAggs.cs).
