### ISSUE TITLE
Cannot save the script as custom action

### ISSUE THREAD

**Issue by scramiro** [m-kovalsky/Tabular#22]
The scrypt to export objects fails.
The error says "Compile failed, custom action contains errors and cannot be saved".
Thanks.

**Comment by m-kovalsky** [comment]
Are you referring to this script?

**Comment by m-kovalsky** [comment]
Are you referring to the script below? In Tabular Editor 2? Running the script or saving the script as a custom action? I just saved this as a custom action with no problem.

https://github.com/m-kovalsky/Tabular/blob/master/ExportReportObjects.cs
