### ISSUE TITLE
Can we run Bestpractices Analyzer directly on .pbix file instead of .bim?

### ISSUE THREAD

**Issue by sai-naresh-1234** [m-kovalsky/Tabular#26]
Hi @m-kovalsky,

Can we run Best practices Analyzer directly on .pbix file instead of .bim or. dataset? 

Do we have any approach to convert .pbix to .bim file?

Thanks

**Comment by m-kovalsky** [comment]
Why not save as a .pbip file and run the BPA against the .bim file contained within the .pbip?

**Comment by sai-naresh-1234** [comment]
> Why not save as a .pbip file and run the BPA against the .bim file contained within the .pbip?

Yes! we can do it. Instead of Power Bi desktop,do we have any other approach to do it?

Thanks

**Comment by m-kovalsky** [comment]
Any other approach to do create the .pbip? No, the only way is to use Power BI Desktop.
