### ISSUE TITLE
Script to ExportBPAResults fails (TE3)

### ISSUE THREAD

**Issue by eudesmcf** [m-kovalsky/Tabular#28]
Hello @m-kovalsky ,

The script gives an error when I try to run it. 

[https://github.com/m-kovalsky/Tabular/blob/master/ExportBPAResults.cs](url)

![image](https://github.com/m-kovalsky/Tabular/assets/23265096/60be4ef5-8bba-42b6-985a-61b98352f556)

Can you help?

**Comment by m-kovalsky** [comment]
I updated the script to account for differences between TE2 & TE3 and inherent changes in how c# is processed in both applications. Now it should work. Thanks for reporting.

**Comment by eudesmcf** [comment]
Hi @m-kovalsky.

The problem continue, I'm using TE3 3.14.

![image](https://github.com/m-kovalsky/Tabular/assets/23265096/30991c2e-2bdc-4c1a-ad74-2a8656112217)

**Comment by m-kovalsky** [comment]
See the script now. Make sure to use the second line instead of the first line when executing in TE3.

**Comment by eudesmcf** [comment]
Hi @m-kovalsky, in TE3 it works when you include the LoadExternalRuleCollectionsAsync method.

```
//using TabularEditor.BestPracticeAnalyzer; // Use this for Tabular Editor 2
using TabularEditor.Shared.BPA; // Use this instead of the first line when using Tabular Editor 3

var bpa = new Analyzer();
bpa.SetModel(Model);
bpa.LoadExternalRuleCollectionsAsync();  // When using Tabular Editor 3

var sb = new System.Text.StringBuilder();
string newline = Environment.NewLine;

sb.Append("RuleCategory" + '\t' + "RuleName" + '\t' + "ObjectName" + '\t' + "ObjectType" + '\t' + "RuleSeverity" + '\t' + "HasFixExpression" + newline);

foreach (var a in bpa.AnalyzeAll().ToList())
{
    sb.Append(a.Rule.Category + '\t' + a.RuleName + '\t' + a.ObjectName + '\t' + a.ObjectType + '\t' + a.Rule.Severity + '\t' + a.CanFix + newline);
}

// Output the results
sb.Output();
```

**Comment by m-kovalsky** [comment]
I updated the [script](https://github.com/m-kovalsky/Tabular/blob/master/ExportBPAResults.cs) for use with TE2. Try it now.
