### ISSUE TITLE
ReportLevelMeasures.cs Error Line 63

### ISSUE THREAD

**Issue by rafaelxkr** [m-kovalsky/Tabular#6]
I tried run script, but don't work this line. 

![image](https://user-images.githubusercontent.com/31570331/122937978-bdc76700-d348-11eb-9796-dd7bc9767605.png)

**Comment by m-kovalsky** [comment]
If you get this error it means that you do not have any report level measures. All your measures are in the model itself.

**Comment by rafaelxkr** [comment]
Thanks!!!!

**Comment by m-kovalsky** [comment]
By the way, I've published v1.0.1 of this script which has a 'try/catch' clause to prevent this error from occurring and display a message as per my previous comment.
