### ISSUE TITLE
ExportReportObjects.cs accumulating report pages when looping through multiple .pbixs

### ISSUE THREAD

**Issue by nsadulski** [m-kovalsky/Tabular#7]
Observing cases where the ReportObjects_Visuals.txt from using "Method 2" for multiple .pbix results in all of the pages from the first report also being associated to the second.  Then all those pages also being associated to the third report.  Then all those pages also being associated to the fourth and so on.

No issue with Method 1 for a single .pbix.

This is an incredibly helpful tool but may create confusion when using across multiple .pbixs.

TE version 2.16.1.

Example: Created 3 .pbixs each having one page.  First .pbix shows the one page correctly, but subsequent reports scanned repeat the report + page listed previously.

![Example](https://user-images.githubusercontent.com/20247860/131186794-58bd690f-9815-4588-950d-8a3da0277fe7.jpg)

**Comment by m-kovalsky** [comment]
Thanks for reporting. This is fixed in v1.0.6 (https://github.com/m-kovalsky/Tabular/blob/master/ExportReportObjects.cs).
