### ISSUE TITLE
ExportReportObjects.cs Error on line 155 (Connections)

### ISSUE THREAD

**Issue by DaniilMaslyuk** [m-kovalsky/Tabular#8]
While my folder path and file name are correct, I get the following error when I try to run the script:
![image](https://user-images.githubusercontent.com/10683126/134617596-d605e74a-87b0-410a-bb53-2d5ca270298b.png)
It's just a simple file I created for test purposes and saved locally. Report elements and the data model are in one PBIX file.

**Comment by m-kovalsky** [comment]
This is fixed in [v1.1.2](https://github.com/m-kovalsky/Tabular/blob/master/ExportReportObjects.cs). The issue occurred if there was no 'Connections' file within the .pbix file. Thanks for reporting.
